# Generated by Django 4.2.7 on 2024-02-25 07:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50, verbose_name='Заголовок')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('content', models.TextField(verbose_name='Контент')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='posts_images', verbose_name='Изображение')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_published', models.BooleanField(choices=[(1, 'Опубликованно'), (0, 'Архив')], db_index=True, default='Опубликованно', verbose_name='Статус')),
                ('views', models.PositiveIntegerField(default=1)),
                ('like_percent', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(limit_value=100)])),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['-time_create'],
            },
        ),
    ]
