# Generated by Django 4.2.1 on 2024-01-27 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='likes',
        ),
    ]
