# Generated by Django 5.0.1 on 2024-01-28 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0005_alter_article_author_alter_article_likes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
    ]
