# Generated by Django 5.0.1 on 2024-01-30 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0006_alter_article_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='like_percent',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='views',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
