# Generated by Django 5.0.1 on 2024-01-31 03:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0007_article_like_percent_article_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='like_percent',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(limit_value=100)]),
        ),
    ]
