# Generated by Django 5.0.1 on 2024-02-06 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0011_alter_article_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Заголовок'),
        ),
    ]
