# Generated by Django 5.0.1 on 2024-02-07 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0013_alter_article_is_published'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
