# Generated by Django 4.2.7 on 2024-02-17 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0014_delete_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-time_create'], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
    ]
