# Generated by Django 4.2.7 on 2024-02-17 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0015_alter_article_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Заголовок'),
        ),
    ]
