# Generated by Django 5.0.1 on 2024-01-27 03:16

import django.core.validators
import users.my_models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('time_create', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['time_create'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True)),
                ('description', models.TextField(blank=True, max_length=300)),
                ('theme', models.CharField(choices=[('#1bc3e0', 'Голубая'), ('#cc1d1f', 'Красная'), ('#141214', 'Темная'), ('#06d606', 'Зеленая'), ('#ab09e0', 'Фиолетовая')], default='Голубая', max_length=20)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('password', models.CharField(blank=True, max_length=20)),
                ('room_avatar', users.my_models.AvatarImageField(default='KamranGram/room_avatars/default_group.jpeg', upload_to='KamranGram/room_avatars', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg'])])),
            ],
            options={
                'verbose_name': 'Комната',
                'verbose_name_plural': 'Комнаты',
                'ordering': ['-time_create'],
            },
        ),
    ]
