# Generated by Django 4.2.7 on 2024-02-25 07:18

import django.core.validators
from django.db import migrations, models
import users.my_models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=200)),
                ('time_send', models.DateTimeField(auto_now_add=True)),
                ('is_changed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['time_send'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, max_length=300, verbose_name='Описание')),
                ('theme', models.CharField(choices=[('#1bc3e0', 'Голубая'), ('#cc1d1f', 'Красная'), ('#141214', 'Темная'), ('#06d606', 'Зеленая'), ('#ab09e0', 'Фиолетовая')], default='Голубая', max_length=20, verbose_name='Тема')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('password', models.CharField(blank=True, max_length=20, verbose_name='Пароль комнаты')),
                ('limit_members', models.PositiveIntegerField(default=2, verbose_name='Лимит участников')),
                ('is_searchable', models.BooleanField(db_index=True, default=True, verbose_name='Доступна для поиска')),
                ('room_avatar', users.my_models.AvatarImageField(default='KamranGram/room_avatars/default_group.png', upload_to='KamranGram/room_avatars', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg'])])),
            ],
            options={
                'verbose_name': 'Комната',
                'verbose_name_plural': 'Комнаты',
                'ordering': ['-time_create'],
            },
        ),
    ]
