# Generated by Django 5.0.1 on 2024-02-02 13:29


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KamranGram', '0003_alter_message_room_alter_message_sender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(),
        ),
    ]
