# Generated by Django 5.0.1 on 2024-02-02 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KamranGram', '0004_alter_message_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(max_length=200),
        ),
    ]
