# Generated by Django 5.0.1 on 2024-02-06 07:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KamranGram', '0005_alter_message_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='time_visit',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 6, 11, 1, 38, 657417)),
        ),
    ]
