# Generated by Django 5.0.1 on 2024-02-06 13:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KamranGram', '0006_room_time_visit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-time_visit'], 'verbose_name': 'Комната', 'verbose_name_plural': 'Комнаты'},
        ),
        migrations.AlterField(
            model_name='room',
            name='time_visit',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 6, 17, 3, 44, 823186)),
        ),
    ]
