# Generated by Django 5.0.1 on 2024-02-06 13:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KamranGram', '0007_alter_room_options_alter_room_time_visit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-last_visit'], 'verbose_name': 'Комната', 'verbose_name_plural': 'Комнаты'},
        ),
        migrations.RemoveField(
            model_name='room',
            name='time_visit',
        ),
        migrations.AddField(
            model_name='room',
            name='last_visit',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 6, 17, 4, 15, 373642)),
        ),
    ]
