# Generated by Django 5.0.1 on 2024-02-06 14:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KamranGram', '0008_alter_room_options_remove_room_time_visit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='last_visit',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 6, 18, 17, 18, 986030)),
        ),
    ]
