# Generated by Django 5.0.1 on 2024-02-07 06:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KamranGram', '0012_alter_room_last_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='last_visit',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 7, 10, 36, 51, 66998)),
        ),
    ]
