# Generated by Django 4.2.7 on 2024-02-09 06:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KamranGram', '0016_alter_message_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='last_visit',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 9, 10, 10, 48, 9307)),
        ),
    ]
