# Generated by Django 4.2.7 on 2024-02-12 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KamranGram', '0020_alter_room_last_visit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['room_messages'], 'verbose_name': 'Комната', 'verbose_name_plural': 'Комнаты'},
        ),
        migrations.RemoveField(
            model_name='room',
            name='last_visit',
        ),
    ]
