# Generated by Django 4.2.7 on 2024-02-12 14:03

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('KamranGram', '0023_alter_room_last_visit_alter_room_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='last_visit',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 12, 18, 3, 40, 602313)),
        ),
        migrations.AlterField(
            model_name='room',
            name='members',
            field=models.ManyToManyField(related_name='current_rooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
