# Generated by Django 4.2.7 on 2024-02-14 06:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KamranGram', '0025_alter_room_last_visit_alter_room_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='last_visit',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 14, 10, 1, 36, 399155)),
        ),
    ]
