# Generated by Django 4.2.7 on 2024-02-14 13:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KamranGram', '0027_alter_room_last_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='last_visit',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 14, 17, 26, 49, 162076)),
        ),
    ]
