# Generated by Django 4.2.7 on 2024-02-14 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_alter_comment_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment_post',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment_video',
            new_name='video',
        ),
    ]
