# Generated by Django 4.2.7 on 2024-02-25 07:18

import KamranVideo.my_models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', KamranVideo.my_models.VideoField(upload_to='KamranVideo/videos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])])),
                ('preview', KamranVideo.my_models.LimitedImageField(help_text='Поддерживаются изображения в формате: 1280 ✕ 720, 1366 ✕ 768, 1920 ✕ 1080', upload_to='KamranVideo/previews', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg'])])),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('title', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('views', models.PositiveIntegerField(default=1)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
            },
        ),
    ]
