# Generated by Django 5.0.1 on 2024-01-28 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KamranVideo', '0003_alter_video_author_alter_video_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'Видео', 'verbose_name_plural': 'Видео'},
        ),
    ]
