# Generated by Django 5.0.1 on 2024-02-03 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KamranVideo', '0005_alter_video_description_alter_video_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='views',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
