# Generated by Django 5.0.1 on 2024-02-06 14:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KamranVideo', '0006_video_views'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='video_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
