# Generated by Django 4.2.7 on 2024-02-17 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KamranVideo', '0008_alter_video_description_alter_video_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
    ]
